import { useEffect, useState } from 'react'
import { getDeviceProperty, getDeviceStates, subscribeDeviceStates } from '../api/devices'
import type { Device, PropertyValue, StateValue } from '../types/device'
import { PropertyControl } from './PropertyControl'

function displayValue(value: PropertyValue): string { if (value.bool !== undefined) return value.bool ? 'true' : 'false'; if (value.number !== undefined) return String(value.number); return value.string ?? '—' }
function mergeState(items: StateValue[], incoming: StateValue): StateValue[] { const index = items.findIndex((item) => item.key.endpointId === incoming.key.endpointId && item.key.capabilityId === incoming.key.capabilityId && item.key.propertyId === incoming.key.propertyId); if (index < 0) return [...items, incoming]; if (items[index].version > incoming.version) return items; return items.map((item, current) => current === index ? incoming : item) }

export function DeviceDetails({ device, onClose, onPropertyWrite }: { device: Device; onClose: () => void; onPropertyWrite: (endpointId: string, capabilityId: string, propertyId: string, value: PropertyValue) => Promise<void> }) {
  const [states, setStates] = useState<StateValue[]>([])
  const [readValues, setReadValues] = useState<Record<string, PropertyValue>>({})
  const [reading, setReading] = useState<string | null>(null)
  const [error, setError] = useState<string | null>(null)
  useEffect(() => { const controller = new AbortController(); void getDeviceStates(device.id, controller.signal).then((items) => { setStates((current) => items.reduce(mergeState, current)); setError(null) }).catch((cause) => { if (!(cause instanceof DOMException && cause.name === 'AbortError')) setError(cause instanceof Error ? cause.message : '状态读取失败') }); const unsubscribe = subscribeDeviceStates(device.id, (state) => setStates((current) => mergeState(current, state))); return () => { controller.abort(); unsubscribe() } }, [device.id])
  useEffect(() => { const close = (event: KeyboardEvent) => { if (event.key === 'Escape') onClose() }; window.addEventListener('keydown', close); return () => window.removeEventListener('keydown', close) }, [onClose])
  const stateFor = (endpointId: string, capabilityId: string, propertyId: string) => states.find((item) => item.key.endpointId === endpointId && item.key.capabilityId === capabilityId && item.key.propertyId === propertyId)
  const readProperty = async (endpointId: string, capabilityId: string, propertyId: string) => { const key = `${endpointId}/${capabilityId}/${propertyId}`; setReading(key); try { const property = await getDeviceProperty(device.id, endpointId, capabilityId, propertyId); setReadValues((current) => ({ ...current, [key]: property.value })); setError(null) } catch (cause) { setError(cause instanceof Error ? cause.message : '属性读取失败') } finally { setReading(null) } }
  return <div className="modal-backdrop"><section className="device-details" role="dialog" aria-label={`${device.name}详情`}><div className="form-heading"><div><p className="eyebrow">DEVICE · {device.providerId}</p><h2>{device.name}</h2><small>{device.id}</small></div><button onClick={onClose}>关闭</button></div>
    <div className="device-detail-summary"><span><i className={`status-dot ${device.online ? 'is-online' : ''}`} />{device.online ? '在线' : '离线'}</span><span>{device.type}</span><span>更新于 {new Date(device.lastUpdateAt).toLocaleString()}</span></div>
    {error && <p className="inline-error">{error}</p>}
    <div className="capability-tree">{device.endpoints.map((endpoint) => <section key={endpoint.id}><div className="tree-heading"><span>ENDPOINT</span><strong>{endpoint.name}</strong><code>{endpoint.id} · {endpoint.type}</code></div>{endpoint.capabilities.map((capability) => <div className="capability-node" key={capability.id}><div><span>CAPABILITY</span><strong>{capability.type}</strong><code>{capability.id}</code></div>{capability.properties.map((property) => { const state = stateFor(endpoint.id, capability.id, property.definition.id); const key = `${endpoint.id}/${capability.id}/${property.definition.id}`; const value = readValues[key] ?? property.value; return <article className="property-node" key={property.definition.id}><div><strong>{property.definition.name}</strong><code>{property.definition.id}</code></div><div className="property-value"><b>{displayValue(value)}{property.definition.unit ? ` ${property.definition.unit}` : ''}</b><span>{property.definition.readable ? 'R' : ''}{property.definition.writable ? 'W' : ''}{property.definition.notifiable ? 'N' : ''}</span>{property.definition.readable && <button disabled={!device.online || reading === key} onClick={() => void readProperty(endpoint.id, capability.id, property.definition.id)}>{reading === key ? '读取中…' : '从 Provider 读取'}</button>}</div><PropertyControl definition={property.definition} value={value} onWrite={(value) => onPropertyWrite(endpoint.id, capability.id, property.definition.id, value)} /><dl><div><dt>来源</dt><dd>{state?.providerId ?? device.providerId} · {state?.source ?? '—'}</dd></div><div><dt>质量</dt><dd><i className={`quality is-${state?.quality ?? 'unknown'}`}>{state?.quality ?? 'unknown'}</i></dd></div><div><dt>版本</dt><dd>{state?.version ?? '—'} / seq {state?.sequence ?? '—'}</dd></div><div><dt>观察时间</dt><dd>{state ? new Date(state.observedAt).toLocaleString() : '—'}</dd></div><div><dt>TTL</dt><dd>{property.definition.staleAfterSeconds ? `${property.definition.staleAfterSeconds}s` : '无'}{state?.expiresAt ? ` · ${new Date(state.expiresAt).toLocaleTimeString()}` : ''}</dd></div><div><dt>待确认命令</dt><dd>{state?.pendingCommandId ?? '无'}</dd></div></dl></article>})}</div>)}</section>)}</div>
  </section></div>
}
