package go2rtc

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"net"
	"net/http"
	"net/url"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"strconv"
	"strings"
	"sync"
	"time"
)

const (
	UpstreamTag    = "v1.9.14"
	UpstreamCommit = "b5948cfb25404cc5cb37b166ecaa2dca20b11d4b"
)

var ErrInvalidConfig = errors.New("invalid go2rtc kernel configuration")

// XiaomiSource contains camera routing metadata plus an optional preauthorized
// MISS handshake. The handshake is passed to go2rtc only through the child
// environment; PublisherSecrets owns the separate Xiaomi account token.
type XiaomiSource struct {
	UserID        string
	Region        string
	LocalIP       string
	DID           string
	Model         string
	Subtype       string
	Channel       int
	ClientPublic  string
	ClientPrivate string
	DevicePublic  string
	Sign          string
	Vendor        string
	UID           string
}

// PublisherSecrets are short-lived process inputs. They are placed in the
// child environment only; the on-disk YAML contains ${ENV_NAME} placeholders.
// The HomeKit private key stays stable across restarts and therefore comes from
// Core's encrypted identity store rather than being generated by this worker.
type PublisherSecrets struct {
	HomeKitPIN           string
	HomeKitDevicePrivate string
}

type HomeKitPublisher struct {
	Name     string
	DeviceID string
	// Pairings seed a recovered publisher. New pairings are written by go2rtc to
	// the protected per-camera config and retained on later starts.
	Pairings []string
}

// PublisherConfig creates one go2rtc process per camera. APIListen is the HAP
// listener advertised to Apple Home; it must be reachable by controllers.
// RTSP remains loopback-only for the local Apple Home publisher integration.
type PublisherConfig struct {
	Binary          string
	FFmpegBinary    string
	RuntimeDir      string
	StreamID        string
	APIListen       string
	MediaUnixSocket string
	RTSPListen      string
	SRTPListen      string
	SourceURI       string
	SourceProtocol  string
	ConnectionMode  string
	Audio           bool
	Xiaomi          XiaomiSource
	Secrets         PublisherSecrets
	HomeKit         HomeKitPublisher
	// PublishHomeKit is explicit desired state from a Camera Target. A source
	// stream without a Target still runs for Device Center preview, but must
	// not advertise or allocate a HomeKit accessory identity.
	PublishHomeKit bool
	LogLevel       string
	LogOutput      io.Writer

	StartupTimeout time.Duration
	StopTimeout    time.Duration
}

// PublisherKernel owns a camera's isolated go2rtc process and protected
// runtime configuration. The parent directory is 0700 and config is repaired
// to 0600 both before start and when the process exits.
type PublisherKernel struct {
	configPath  string
	output      PublisherOutput
	cmd         *exec.Cmd
	stopTimeout time.Duration
	done        <-chan error
	diagnostics *publisherDiagnosticLog

	mu      sync.Mutex
	stopped bool
}

type PublisherOutput struct {
	RTSPURL  string
	HAPHost  string
	StreamID string
	Name     string
	PIN      string
	LogPath  string
}

var errPublisherExitedDuringStart = errors.New("camera publisher exited during start")

func verifyBinary(ctx context.Context, binary string) error {
	check, cancel := context.WithTimeout(ctx, 5*time.Second)
	defer cancel()
	output, err := exec.CommandContext(check, binary, "-version").Output()
	if err != nil {
		return fmt.Errorf("verify HomeLoom camera kernel: %w", err)
	}
	if !bytes.Contains(output, []byte("go2rtc version 1.9.14-homeloom.1")) {
		return errors.New("camera kernel does not match HomeLoom pinned version")
	}
	return nil
}

func StartPublisher(ctx context.Context, config PublisherConfig) (*PublisherKernel, error) {
	config = config.withDefaults()
	if err := config.validate(); err != nil {
		return nil, err
	}
	if err := verifyBinary(ctx, config.Binary); err != nil {
		return nil, err
	}
	if err := verifyExecutable(config.FFmpegBinary, "FFmpeg"); err != nil {
		return nil, err
	}

	directory := filepath.Join(config.RuntimeDir, config.StreamID)
	if err := os.MkdirAll(directory, 0o700); err != nil {
		return nil, fmt.Errorf("create publisher runtime directory: %w", err)
	}
	if err := os.Chmod(config.RuntimeDir, 0o700); err != nil {
		return nil, fmt.Errorf("secure publisher runtime root: %w", err)
	}
	if err := os.Chmod(directory, 0o700); err != nil {
		return nil, fmt.Errorf("secure publisher runtime directory: %w", err)
	}
	diagnostics, err := openPublisherDiagnosticLog(directory, config.LogOutput)
	if err != nil {
		return nil, err
	}
	diagnosticsOwnedByPublisher := false
	defer func() {
		if !diagnosticsOwnedByPublisher {
			_ = diagnostics.Close()
		}
	}()
	diagnostics.Event("info", "camera publisher start requested", map[string]any{
		"stream_id":       config.StreamID,
		"source_protocol": config.SourceProtocol,
		"connection_mode": config.ConnectionMode,
		"homekit_enabled": config.PublishHomeKit,
	})
	identity := publisherIdentity{}
	if config.PublishHomeKit {
		identity, err = ensureIdentity(directory, config.Secrets.HomeKitPIN, config.HomeKit.DeviceID, config.Secrets.HomeKitDevicePrivate)
		if err != nil {
			diagnostics.Event("error", "camera publisher identity initialization failed", map[string]any{"stream_id": config.StreamID})
			return nil, err
		}
		config.Secrets.HomeKitPIN = identity.PIN
		config.Secrets.HomeKitDevicePrivate = identity.DevicePrivate
		config.HomeKit.DeviceID = identity.DeviceID
	}
	configPath := filepath.Join(directory, "go2rtc.yaml")
	durablePairingsPath := durableHomeKitPairingsPath(config.RuntimeDir, config.StreamID)
	// Prefer the durable pairings store. go2rtc.yaml is rewritten by upgrades and
	// preview toggles, so it is only a compatibility mirror.
	if len(config.HomeKit.Pairings) == 0 {
		if pairings, ok := readDurableHomeKitPairings(durablePairingsPath); ok {
			config.HomeKit.Pairings = pairings
		} else if pairings, ok := readPersistedHomeKitPairings(configPath, config.StreamID); ok {
			config.HomeKit.Pairings = pairings
		}
	}
	if len(config.HomeKit.Pairings) > 0 {
		if err := writeDurableHomeKitPairings(durablePairingsPath, config.StreamID, config.HomeKit.Pairings); err != nil {
			return nil, fmt.Errorf("persist HomeKit pairings: %w", err)
		}
	}
	if err := writePublisherConfig(configPath, config); err != nil {
		diagnostics.Event("error", "camera publisher configuration failed", map[string]any{"stream_id": config.StreamID})
		return nil, err
	}
	if err := ensureHomeKitPairingsInConfig(configPath, config); err != nil {
		diagnostics.Event("error", "camera publisher pairing recovery failed", map[string]any{"stream_id": config.StreamID})
		return nil, fmt.Errorf("reseed HomeKit pairings into publisher config: %w", err)
	}

	cmd := exec.Command(config.Binary, "-config", configPath)
	cmd.Env = append(os.Environ(), publisherEnvironment(config)...)
	// Camera Kernel replaces registered source credentials, HomeKit PINs and
	// private keys before writing stdout/stderr. Capture only that redacted
	// stream; never log the child environment from Core.
	cmd.Stdout = diagnostics
	cmd.Stderr = diagnostics
	if err := cmd.Start(); err != nil {
		diagnostics.Event("error", "camera publisher process failed to start", map[string]any{"stream_id": config.StreamID})
		return nil, fmt.Errorf("start camera publisher: %w", err)
	}

	publisher := &PublisherKernel{
		configPath: configPath, cmd: cmd, stopTimeout: config.StopTimeout, diagnostics: diagnostics,
		output: PublisherOutput{RTSPURL: "rtsp://" + config.RTSPListen + "/" + config.StreamID, HAPHost: config.APIListen, StreamID: config.StreamID, Name: config.HomeKit.Name, PIN: identity.PIN, LogPath: diagnostics.Path()},
	}
	diagnosticsOwnedByPublisher = true
	diagnostics.Event("info", "camera publisher process started", map[string]any{
		"stream_id": config.StreamID,
		"pid":       cmd.Process.Pid,
	})
	publisher.done = publisher.watchProcess()
	deadline, cancel := context.WithTimeout(ctx, config.StartupTimeout)
	defer cancel()
	tcpAddresses := []string{config.RTSPListen}
	if config.PublishHomeKit {
		tcpAddresses = append(tcpAddresses, config.APIListen)
	}
	if err := waitForPublisherReady(deadline, publisher.done, tcpListenerReady, tcpAddresses...); err != nil {
		diagnostics.Event("error", "camera publisher TCP listeners did not become ready", map[string]any{"stream_id": config.StreamID})
		if !errors.Is(err, errPublisherExitedDuringStart) {
			_ = publisher.Close(context.Background())
		}
		return nil, err
	}
	if err := waitForPublisherReady(deadline, publisher.done, unixListenerReady, config.MediaUnixSocket); err != nil {
		diagnostics.Event("error", "camera publisher media listener did not become ready", map[string]any{"stream_id": config.StreamID})
		if !errors.Is(err, errPublisherExitedDuringStart) {
			_ = publisher.Close(context.Background())
		}
		return nil, err
	}
	diagnostics.Event("info", "camera publisher ready", map[string]any{
		"stream_id":       config.StreamID,
		"hap_address":     config.APIListen,
		"rtsp_address":    config.RTSPListen,
		"srtp_address":    config.SRTPListen,
		"homekit_enabled": config.PublishHomeKit,
	})
	if config.ConnectionMode != "on_demand" {
		// Preloading is an availability optimization, not a publisher liveness
		// requirement. Xiaomi MISS and some ONVIF cameras may need longer than
		// the process startup deadline to deliver their first IDR. Keeping the
		// listeners alive lets later preview/HomeKit requests reuse the same
		// publisher and retry the upstream connection instead of turning one
		// slow camera into a streams.replay reconnect loop.
		dialer := &net.Dialer{}
		client := &http.Client{Transport: &http.Transport{
			Proxy: nil,
			DialContext: func(ctx context.Context, _, _ string) (net.Conn, error) {
				return dialer.DialContext(ctx, "unix", config.MediaUnixSocket)
			},
		}}
		go func() {
			if err := warmPublisherMedia(config.StartupTimeout, client, "media", config.StreamID); err != nil {
				// Preview→HomeKit restarts cancel the previous warmup; treat
				// expected teardown as non-failure noise.
				if errors.Is(err, context.Canceled) || errors.Is(err, context.DeadlineExceeded) ||
					strings.Contains(err.Error(), "EOF") || strings.Contains(err.Error(), "connection refused") {
					diagnostics.Event("info", "camera media warmup interrupted", map[string]any{
						"stream_id": config.StreamID,
						"error":     err.Error(),
					})
					return
				}
				diagnostics.Event("warn", "camera media warmup failed", map[string]any{
					"stream_id": config.StreamID,
					"error":     err.Error(),
				})
				return
			}
			diagnostics.Event("info", "camera media warmup ready", map[string]any{"stream_id": config.StreamID})
		}()
	}
	return publisher, nil
}

func verifyExecutable(path, name string) error {
	path = filepath.Clean(path)
	info, err := os.Stat(path)
	if err != nil {
		return fmt.Errorf("%s executable %q is unavailable: %w", name, path, err)
	}
	if !info.Mode().IsRegular() || info.Mode().Perm()&0o111 == 0 {
		return fmt.Errorf("%s executable %q is not an executable file", name, path)
	}
	return nil
}

func warmPublisherMedia(timeout time.Duration, client publisherHTTPClient, apiAddress, streamID string) error {
	ctx, cancel := context.WithTimeout(context.Background(), timeout)
	defer cancel()
	// The readiness request itself drives an H.264 consumer. Failure is
	// deliberately non-fatal: preload falls back to the normal on-demand retry.
	return waitForPublisherMediaReady(ctx, client, apiAddress, streamID)
}

type listenerProbe func(string) bool

func waitForPublisherReady(ctx context.Context, done <-chan error, probe listenerProbe, addresses ...string) error {
	ticker := time.NewTicker(50 * time.Millisecond)
	defer ticker.Stop()
	for {
		ready := true
		for _, address := range addresses {
			if !probe(loopbackDialAddress(address)) {
				ready = false
				break
			}
		}
		if ready {
			return nil
		}
		select {
		case err := <-done:
			if err == nil {
				err = errors.New("process exited")
			}
			return fmt.Errorf("%w: %v", errPublisherExitedDuringStart, err)
		case <-ticker.C:
		case <-ctx.Done():
			return errors.New("camera publisher listeners did not become ready")
		}
	}
}

func tcpListenerReady(address string) bool {
	connection, err := net.DialTimeout("tcp", address, 100*time.Millisecond)
	if err != nil {
		return false
	}
	_ = connection.Close()
	return true
}

func unixListenerReady(path string) bool {
	connection, err := net.DialTimeout("unix", path, 100*time.Millisecond)
	if err != nil {
		return false
	}
	_ = connection.Close()
	return true
}

func loopbackDialAddress(address string) string {
	host, port, err := net.SplitHostPort(address)
	if err != nil {
		return address
	}
	ip := net.ParseIP(host)
	switch {
	case host == "" || (ip != nil && ip.IsUnspecified() && ip.To4() != nil):
		host = "127.0.0.1"
	case ip != nil && ip.IsUnspecified():
		host = "::1"
	}
	return net.JoinHostPort(host, port)
}

type publisherHTTPClient interface {
	Do(*http.Request) (*http.Response, error)
}

func waitForPublisherMediaReady(ctx context.Context, client publisherHTTPClient, apiAddress, streamID string) error {
	endpoint := url.URL{
		Scheme: "http",
		Host:   loopbackDialAddress(apiAddress),
		Path:   "/api/frame.mp4",
	}
	query := endpoint.Query()
	query.Set("src", streamID)
	query.Set("video", "h264")
	endpoint.RawQuery = query.Encode()

	request, err := http.NewRequestWithContext(ctx, http.MethodGet, endpoint.String(), nil)
	if err != nil {
		return err
	}
	request.Header.Set("User-Agent", "HomeLoom-Media-Readiness/1")
	response, err := client.Do(request)
	if err != nil {
		return err
	}
	defer response.Body.Close()
	if response.StatusCode != http.StatusOK {
		return fmt.Errorf("unexpected readiness status %d", response.StatusCode)
	}
	contentType := strings.ToLower(response.Header.Get("Content-Type"))
	if !strings.HasPrefix(contentType, "video/mp4") || !strings.Contains(contentType, "avc1") {
		return errors.New("readiness response was not H.264 MP4")
	}
	payload, err := io.ReadAll(io.LimitReader(response.Body, 8<<20))
	if err != nil {
		return err
	}
	if !strings.Contains(string(payload), "moof") {
		return errors.New("readiness response did not contain a media fragment")
	}
	return nil
}

func (c PublisherConfig) withDefaults() PublisherConfig {
	if c.LogLevel == "" {
		c.LogLevel = "info"
	}
	if c.Binary == "" {
		c.Binary = "homeloom-camera-kernel"
	}
	if c.FFmpegBinary == "" {
		c.FFmpegBinary = filepath.Join(filepath.Dir(c.Binary), "ffmpeg")
	}
	if c.ConnectionMode == "" {
		c.ConnectionMode = "on_demand"
	}
	if c.MediaUnixSocket == "" && c.RuntimeDir != "" && c.StreamID != "" {
		c.MediaUnixSocket = filepath.Join(c.RuntimeDir, c.StreamID, "media.sock")
	}
	if c.StartupTimeout <= 0 {
		c.StartupTimeout = 10 * time.Second
	}
	if c.StopTimeout <= 0 {
		c.StopTimeout = 5 * time.Second
	}
	return c
}

func (c PublisherConfig) validate() error {
	c = c.withDefaults()
	switch c.LogLevel {
	case "debug", "info", "warn", "error":
	default:
		return fmt.Errorf("%w: invalid camera kernel log level", ErrInvalidConfig)
	}
	sourceURI := c.SourceURI
	if sourceURI == "" {
		sourceURI = c.Xiaomi.URI()
	}
	parsedSource, sourceErr := url.Parse(sourceURI)
	sourceProtocol := c.SourceProtocol
	if sourceProtocol == "" && parsedSource != nil {
		sourceProtocol = parsedSource.Scheme
		if sourceProtocol == "xiaomi" {
			sourceProtocol = "xiaomi-miss"
		}
	}
	if !filepath.IsAbs(c.RuntimeDir) || !filepath.IsAbs(c.MediaUnixSocket) || !validPublisherID(c.StreamID) || sourceErr != nil || parsedSource.Host == "" ||
		!allowedSourceScheme(parsedSource.Scheme) || !sourceSchemeMatches(sourceProtocol, parsedSource.Scheme) ||
		!validConnectionMode(c.ConnectionMode) ||
		(c.PublishHomeKit && c.HomeKit.Name == "") {
		return ErrInvalidConfig
	}
	for _, address := range []string{c.RTSPListen, c.SRTPListen} {
		if _, _, err := net.SplitHostPort(address); err != nil {
			return ErrInvalidConfig
		}
	}
	if c.PublishHomeKit {
		if _, _, err := net.SplitHostPort(c.APIListen); err != nil {
			return ErrInvalidConfig
		}
	}
	if host, _, _ := net.SplitHostPort(c.RTSPListen); !net.ParseIP(host).IsLoopback() {
		return ErrInvalidConfig
	}
	return nil
}

func (p *PublisherKernel) Output() PublisherOutput { return p.output }
func (p *PublisherKernel) ConfigPath() string      { return p.configPath }

func (p *PublisherKernel) Close(ctx context.Context) error {
	p.mu.Lock()
	if p.stopped {
		p.mu.Unlock()
		return nil
	}
	p.stopped = true
	cmd := p.cmd
	p.mu.Unlock()
	if cmd == nil || cmd.Process == nil {
		return nil
	}
	p.diagnostics.Event("info", "camera publisher stop requested", map[string]any{"stream_id": p.output.StreamID})
	_ = cmd.Process.Signal(os.Interrupt)
	stop, cancel := context.WithTimeout(ctx, p.stopTimeout)
	defer cancel()
	select {
	case <-stop.Done():
		_ = cmd.Process.Kill()
		<-p.done
		return stop.Err()
	case err := <-p.done:
		if err != nil {
			return fmt.Errorf("camera publisher exited: %w", err)
		}
		return nil
	}
}

func (p *PublisherKernel) repairConfigPermissions() error {
	if err := os.Chmod(filepath.Dir(p.configPath), 0o700); err != nil {
		return err
	}
	if err := os.Chmod(p.configPath, 0o600); err != nil {
		return err
	}
	return nil
}

func (p *PublisherKernel) watchProcess() <-chan error {
	done := make(chan error, 1)
	go func() {
		err := p.cmd.Wait()
		_ = p.repairConfigPermissions()
		fields := map[string]any{"stream_id": p.output.StreamID}
		if err != nil {
			fields["error"] = err.Error()
			p.diagnostics.Event("error", "camera publisher process exited", fields)
		} else {
			p.diagnostics.Event("info", "camera publisher process exited", fields)
		}
		_ = p.diagnostics.Close()
		done <- err
	}()
	return done
}

const durableHomeKitPairingsFilename = "homekit-pairings.json"

func durableHomeKitPairingsPath(runtimeDir, streamID string) string {
	return filepath.Join(runtimeDir, streamID, durableHomeKitPairingsFilename)
}

func readDurableHomeKitPairings(path string) ([]string, bool) {
	raw, err := os.ReadFile(path)
	if err != nil {
		return nil, false
	}
	var document struct {
		SchemaVersion int      `json:"schemaVersion"`
		StreamID      string   `json:"streamId"`
		Pairings      []string `json:"pairings"`
	}
	if err := json.Unmarshal(raw, &document); err != nil || document.SchemaVersion != 1 {
		return nil, false
	}
	pairings := make([]string, 0, len(document.Pairings))
	for _, pairing := range document.Pairings {
		pairing = strings.TrimSpace(pairing)
		if pairing != "" {
			pairings = append(pairings, pairing)
		}
	}
	return pairings, true
}

func writeDurableHomeKitPairings(path, streamID string, pairings []string) error {
	clean := make([]string, 0, len(pairings))
	for _, pairing := range pairings {
		pairing = strings.TrimSpace(pairing)
		if pairing != "" {
			clean = append(clean, pairing)
		}
	}
	raw, err := json.Marshal(struct {
		SchemaVersion int      `json:"schemaVersion"`
		StreamID      string   `json:"streamId"`
		Pairings      []string `json:"pairings"`
	}{SchemaVersion: 1, StreamID: streamID, Pairings: clean})
	if err != nil {
		return err
	}
	tmp := path + ".tmp"
	if err := os.WriteFile(tmp, raw, 0o600); err != nil {
		return err
	}
	if err := os.Rename(tmp, path); err != nil {
		_ = os.Remove(tmp)
		return err
	}
	return os.Chmod(path, 0o600)
}

func readPersistedHomeKitPairings(path, streamID string) ([]string, bool) {
	raw, err := os.ReadFile(path)
	if err != nil {
		return nil, false
	}
	// Keep parsing tolerant: go2rtc may rewrite formatting, and pairings are
	// the only field required for accessory recovery.
	if !strings.Contains(string(raw), "\nhomekit:\n") {
		return nil, false
	}
	// Minimal YAML extraction without pulling gopkg dependency into more paths:
	// look for the stream section pairings list.
	lines := strings.Split(string(raw), "\n")
	inHomeKit := false
	inStream := false
	inPairings := false
	streamKey := strconv.Quote(streamID) + ":"
	streamKeyBare := streamID + ":"
	var pairings []string
	for _, line := range lines {
		trimmed := strings.TrimSpace(line)
		if trimmed == "homekit:" {
			inHomeKit = true
			inStream = false
			inPairings = false
			continue
		}
		if !inHomeKit {
			continue
		}
		if line != "" && !strings.HasPrefix(line, " ") && !strings.HasPrefix(line, "\t") {
			break
		}
		if strings.HasPrefix(strings.TrimLeft(line, " \t"), streamKey) || strings.HasPrefix(strings.TrimLeft(line, " \t"), streamKeyBare) {
			inStream = true
			inPairings = false
			continue
		}
		if !inStream {
			continue
		}
		// another stream under homekit
		indent := len(line) - len(strings.TrimLeft(line, " "))
		if trimmed != "" && !strings.HasPrefix(trimmed, "#") && indent > 0 && indent <= 2 && strings.HasSuffix(trimmed, ":") && trimmed != "pairings:" {
			// left current stream block
			inStream = false
			inPairings = false
			continue
		}
		if trimmed == "pairings: []" {
			return []string{}, true
		}
		if trimmed == "pairings:" {
			inPairings = true
			continue
		}
		if inPairings {
			if strings.HasPrefix(trimmed, "- ") {
				value := strings.TrimSpace(strings.TrimPrefix(trimmed, "- "))
				if strings.HasPrefix(value, "\"") && strings.HasSuffix(value, "\"") {
					if unquoted, err := strconv.Unquote(value); err == nil {
						value = unquoted
					}
				}
				pairings = append(pairings, value)
				continue
			}
			if trimmed == "" || strings.HasPrefix(trimmed, "#") {
				continue
			}
			break
		}
	}
	if pairings == nil {
		return nil, false
	}
	return pairings, true
}

func ensureHomeKitPairingsInConfig(path string, config PublisherConfig) error {
	if !config.PublishHomeKit {
		return nil
	}
	raw, err := os.ReadFile(path)
	if err != nil {
		return err
	}
	current, ok := readPersistedHomeKitPairings(path, config.StreamID)
	if ok && len(current) > 0 {
		return nil
	}
	if len(config.HomeKit.Pairings) == 0 {
		return nil
	}
	updated := string(raw)
	// Replace empty pairings list with durable values.
	replacement := "    pairings:\n"
	for _, pairing := range config.HomeKit.Pairings {
		replacement += "      - " + yamlString(pairing) + "\n"
	}
	if strings.Contains(updated, "    pairings: []\n") {
		updated = strings.Replace(updated, "    pairings: []\n", replacement, 1)
	} else if strings.Contains(updated, "    pairings:\n") {
		// leave non-empty as-is
		return nil
	} else {
		// append under stream homekit block end
		updated = strings.TrimRight(updated, "\n") + "\n" + replacement
	}
	if err := os.WriteFile(path, []byte(updated), 0o600); err != nil {
		return err
	}
	return os.Chmod(path, 0o600)
}

func writePublisherConfig(path string, config PublisherConfig) error {
	info, err := os.Lstat(path)
	switch {
	case err == nil && !info.Mode().IsRegular():
		return errors.New("publisher config path is not a regular file")
	case err == nil:
		existing, readErr := os.ReadFile(path)
		if readErr != nil {
			return fmt.Errorf("read publisher config: %w", readErr)
		}
		hasHomeKit := strings.Contains(string(existing), "\nhomekit:\n")
		switch {
		case !config.PublishHomeKit:
			// Camera Kernel initializes every compiled module. The app.modules
			// allow-list is documentation, not a runtime gate, so retaining a
			// top-level homekit section would start a half-configured HAP server
			// during the preview-only phase. Move any legacy YAML pairings into
			// the durable sidecar before replacing the runtime configuration.
			if hasHomeKit {
				if pairings, ok := readPersistedHomeKitPairings(path, config.StreamID); ok && len(pairings) > 0 {
					durablePath := durableHomeKitPairingsPath(config.RuntimeDir, config.StreamID)
					if err := writeDurableHomeKitPairings(durablePath, config.StreamID, pairings); err != nil {
						return fmt.Errorf("preserve HomeKit pairings before preview-only restart: %w", err)
					}
				}
			}
			if err := os.WriteFile(path, []byte(publisherYAML(config)), 0o600); err != nil {
				return fmt.Errorf("replace preview-only publisher config: %w", err)
			}
		case !hasHomeKit:
			// The normal lifecycle starts as preview-only and later gains a
			// Camera Target. There are no pairings to preserve in that file, so
			// replace it with the complete HomeKit configuration.
			if err := os.WriteFile(path, []byte(publisherYAML(config)), 0o600); err != nil {
				return fmt.Errorf("promote preview publisher to HomeKit: %w", err)
			}
		default:
			// Existing config is authoritative for HomeKit pairings. It may have
			// been rewritten 0644 by upstream PatchConfig. Apply additive,
			// secret-free preview support without replacing the pairing identity.
			if err := upgradePublisherConfig(path, config); err != nil {
				return err
			}
		}
		return os.Chmod(path, 0o600)
	case os.IsNotExist(err):
		if err := os.WriteFile(path, []byte(publisherYAML(config)), 0o600); err != nil {
			return fmt.Errorf("write publisher config: %w", err)
		}
		return os.Chmod(path, 0o600)
	default:
		return fmt.Errorf("inspect publisher config: %w", err)
	}
}

func publisherYAML(config PublisherConfig) string {
	config = config.withDefaults()
	streamURI := "${" + sourceEnv(config) + "}"
	var builder strings.Builder
	builder.WriteString(publisherLogConfig(config.LogLevel))
	builder.WriteString("api:\n  listen: \"\"\n")
	builder.WriteString("  unix_listen: " + yamlString(config.MediaUnixSocket) + "\n")
	if config.PublishHomeKit {
		builder.WriteString("  hap_listen: " + yamlString(config.APIListen) + "\n")
	}
	builder.WriteString("  allow_paths: [" + publisherAllowedPaths(config.PublishHomeKit) + "]\n")
	builder.WriteString("rtsp:\n  listen: " + yamlString(config.RTSPListen) + "\n")
	builder.WriteString("srtp:\n  listen: " + yamlString(config.SRTPListen) + "\n")
	builder.WriteString("exec:\n  allow_paths: [" + yamlString(config.FFmpegBinary) + "]\n")
	builder.WriteString("ffmpeg:\n  bin: " + yamlString(config.FFmpegBinary) + "\n")
	builder.WriteString("  global: " + yamlString(publisherFFmpegGlobal()) + "\n")
	if template := ffmpegH264Template(); template != "" {
		builder.WriteString("  h264: " + yamlString(template) + "\n")
	}
	// Follow go2rtc's documented codec-negotiation layout: preserve a native
	// H.264 stream when available, then try OS hardware paths before software.
	builder.WriteString("streams:\n  " + yamlString(config.StreamID) + ": " + streamProducerListYAML(streamURI, sharedTranscodeURIs(config.StreamID)) + "\n")
	if query := preloadQuery(config.ConnectionMode, config.Audio); query != "" {
		builder.WriteString("preload:\n  " + yamlString(config.StreamID) + ": " + yamlString(query) + "\n")
	}
	if config.PublishHomeKit {
		builder.WriteString("homekit:\n  " + yamlString(config.StreamID) + ":\n")
		builder.WriteString("    name: " + yamlString(config.HomeKit.Name) + "\n")
		builder.WriteString("    pin: \"${" + homeKitPINEnv(config) + "}\"\n")
		builder.WriteString("    device_id: " + yamlString(config.HomeKit.DeviceID) + "\n")
		if config.Secrets.HomeKitDevicePrivate != "" {
			builder.WriteString("    device_private: \"${" + homeKitPrivateEnv(config) + "}\"\n")
		}
	}
	if config.PublishHomeKit {
		if len(config.HomeKit.Pairings) == 0 {
			builder.WriteString("    pairings: []\n")
		} else {
			builder.WriteString("    pairings:\n")
			for _, pairing := range config.HomeKit.Pairings {
				builder.WriteString("      - " + yamlString(pairing) + "\n")
			}
		}
	}
	return builder.String()
}

func upgradePublisherConfig(path string, config PublisherConfig) error {
	config = config.withDefaults()
	content, err := os.ReadFile(path)
	if err != nil {
		return fmt.Errorf("read publisher config: %w", err)
	}
	updated := removePublisherAppConfig(string(content))
	updated = applyPublisherLogConfig(updated, config.LogLevel)
	apiPrefix := "api:\n"
	if index := strings.Index(updated, apiPrefix); index >= 0 {
		blockEnd := len(updated)
		cursor := index + len(apiPrefix)
		for cursor < len(updated) {
			next := strings.IndexByte(updated[cursor:], '\n')
			if next < 0 {
				break
			}
			next += cursor + 1
			if next < len(updated) && updated[next] != ' ' && updated[next] != '\n' {
				blockEnd = next
				break
			}
			cursor = next
		}
		apiHeader := "api:\n  listen: \"\"\n  unix_listen: " + yamlString(config.MediaUnixSocket) + "\n"
		if config.PublishHomeKit {
			apiHeader += "  hap_listen: " + yamlString(config.APIListen) + "\n"
		}
		apiHeader += "  allow_paths: [" + publisherAllowedPaths(config.PublishHomeKit) + "]\n"
		updated = updated[:index] + apiHeader + updated[blockEnd:]
	}
	if !strings.Contains(updated, "\nffmpeg:\n") {
		updated = strings.Replace(updated, "\nstreams:\n",
			"\nexec:\n  allow_paths: ["+yamlString(config.FFmpegBinary)+"]\nffmpeg:\n  bin: "+yamlString(config.FFmpegBinary)+"\nstreams:\n", 1)
	} else if !strings.Contains(updated, "\nexec:\n") {
		updated = strings.Replace(updated, "\nffmpeg:\n",
			"\nexec:\n  allow_paths: ["+yamlString(config.FFmpegBinary)+"]\nffmpeg:\n", 1)
	}
	if template := ffmpegH264Template(); template != "" {
		updated = applyFFmpegH264Template(updated, template)
	}
	updated = applyFFmpegGlobal(updated, publisherFFmpegGlobal())
	streamPrefix := "  " + yamlString(config.StreamID) + ": "
	lines := strings.Split(updated, "\n")
	for index, line := range lines {
		if strings.HasPrefix(line, streamPrefix) {
			lines[index] = streamPrefix + streamProducerListYAML("${"+sourceEnv(config)+"}", sharedTranscodeURIs(config.StreamID))
			break
		}
	}
	updated = strings.Join(lines, "\n")
	updated = applyPreloadConfig(updated, config)
	if updated == string(content) {
		return nil
	}
	if err := os.WriteFile(path, []byte(updated), 0o600); err != nil {
		return fmt.Errorf("upgrade publisher config: %w", err)
	}
	return nil
}

func publisherAllowedPaths(publishHomeKit bool) string {
	if publishHomeKit {
		return "/pair-setup, /pair-verify, /api/stream.mp4, /api/frame.mp4, /api/frame.jpeg, /api/homekit/session, /api/matter/webrtc"
	}
	return "/api/stream.mp4, /api/frame.mp4, /api/frame.jpeg, /api/matter/webrtc"
}

func removePublisherAppConfig(content string) string {
	lines := strings.Split(content, "\n")
	inApp := false
	filtered := make([]string, 0, len(lines))
	for _, line := range lines {
		if line == "app:" {
			inApp = true
			continue
		}
		if inApp {
			if line == "" || strings.HasPrefix(line, "  ") {
				continue
			}
			inApp = false
		}
		filtered = append(filtered, line)
	}
	return strings.Join(filtered, "\n")
}

func publisherLogConfig(level string) string {
	// output defaults to stdout and exec inherits the global level. FFmpeg is
	// explicit because its setting also controls the child process `-v` flag.
	// Keep HomeKit explicit because Camera Kernel's normal default is warn.
	return "log:\n  format: json\n  level: " + level + "\n  time: ISO8601\n  homekit: " + level + "\n  ffmpeg: " + level + "\n"
}

func applyPublisherLogConfig(content, level string) string {
	lines := strings.Split(content, "\n")
	filtered := make([]string, 0, len(lines))
	for index := 0; index < len(lines); {
		if lines[index] == "log:" {
			index++
			for index < len(lines) && (strings.HasPrefix(lines[index], "  ") || lines[index] == "") {
				index++
			}
			continue
		}
		filtered = append(filtered, lines[index])
		index++
	}
	content = strings.Join(filtered, "\n")
	if marker := strings.Index(content, "api:\n"); marker >= 0 {
		return content[:marker] + publisherLogConfig(level) + content[marker:]
	}
	return strings.TrimRight(content, "\n") + "\n" + publisherLogConfig(level)
}

func transcodeURI(streamID string) string {
	uris := sharedTranscodeURIs(streamID)
	return uris[len(uris)-1]
}

func sharedTranscodeURIs(streamID string) []string {
	return transcodeFallbackURIs(streamID, []string{
		"audio=opus/16000",
		"width=1280",
		"height=720",
	})
}

func streamProducerListYAML(native string, fallbacks []string) string {
	parts := make([]string, 0, 1+len(fallbacks))
	parts = append(parts, yamlString(native))
	for _, uri := range fallbacks {
		parts = append(parts, yamlString(uri))
	}
	return "[" + strings.Join(parts, ", ") + "]"
}

// transcodeFallbackURIs builds the shared always-on H.264 producer chain.
// Xiaomi MISS HEVC on macOS fails VideoToolbox hardware decode mid-GOP, so
// Darwin uses software decode + libx264 only. Other platforms may still try
// hardware encode-only before falling back to software.
func transcodeFallbackURIs(streamID string, query []string) []string {
	join := func(videoParts ...string) string {
		uri := "ffmpeg:" + streamID
		for _, part := range videoParts {
			if part != "" {
				uri += "#" + part
			}
		}
		for _, part := range query {
			if part != "" {
				uri += "#" + part
			}
		}
		return uri
	}
	software := join("video=h264")
	switch runtime.GOOS {
	case "darwin":
		// Do not attempt #hardware=videotoolbox (HEVC hard-decode). It fails
		// on incomplete reference frames from MISS and costs ~2s per session.
		return []string{software}
	case "windows":
		return []string{
			join("video=h264/dxva2", "starttimeout=8"),
			join("video=h264/cuda", "starttimeout=8"),
			software,
		}
	default:
		return []string{
			join("video=h264#hardware=vaapi", "starttimeout=8"),
			join("video=h264/cuda", "starttimeout=8"),
			join("video=h264/v4l2m2m", "starttimeout=8"),
			join("video=h264/rkmpp", "starttimeout=8"),
			software,
		}
	}
}

func applyFFmpegH264Template(content, template string) string {
	lines := strings.Split(content, "\n")
	ffmpegIndex := -1
	for index, line := range lines {
		if line == "ffmpeg:" {
			ffmpegIndex = index
			continue
		}
		if ffmpegIndex < 0 {
			continue
		}
		if strings.HasPrefix(line, "  h264:") {
			lines[index] = "  h264: " + yamlString(template)
			return strings.Join(lines, "\n")
		}
		if line != "" && !strings.HasPrefix(line, "  ") {
			lines = append(lines[:index], append([]string{"  h264: " + yamlString(template)}, lines[index:]...)...)
			return strings.Join(lines, "\n")
		}
	}
	if ffmpegIndex >= 0 {
		lines = append(lines, "  h264: "+yamlString(template))
	}
	return strings.Join(lines, "\n")
}

func publisherFFmpegGlobal() string {
	// Preserve FFmpeg warnings and startup metadata while suppressing the
	// half-second encoding progress line that otherwise hides HAP events.
	return "-hide_banner -nostats"
}

func applyFFmpegGlobal(content, value string) string {
	lines := strings.Split(content, "\n")
	ffmpegIndex := -1
	for index, line := range lines {
		if line == "ffmpeg:" {
			ffmpegIndex = index
			continue
		}
		if ffmpegIndex < 0 {
			continue
		}
		if strings.HasPrefix(line, "  global:") {
			lines[index] = "  global: " + yamlString(value)
			return strings.Join(lines, "\n")
		}
		if line != "" && !strings.HasPrefix(line, "  ") {
			lines = append(lines[:index], append([]string{"  global: " + yamlString(value)}, lines[index:]...)...)
			return strings.Join(lines, "\n")
		}
	}
	if ffmpegIndex >= 0 {
		lines = append(lines, "  global: "+yamlString(value))
	}
	return strings.Join(lines, "\n")
}

func preloadQuery(mode string, audio bool) string {
	switch mode {
	case "preload":
		return "video"
	case "always_on":
		if audio {
			return "video=h264&audio=opus"
		}
		return "video=h264"
	default:
		return ""
	}
}

func validConnectionMode(mode string) bool {
	return mode == "on_demand" || mode == "preload" || mode == "always_on"
}

func applyPreloadConfig(content string, config PublisherConfig) string {
	lines := strings.Split(content, "\n")
	filtered := make([]string, 0, len(lines))
	for index := 0; index < len(lines); {
		if lines[index] == "preload:" {
			index++
			for index < len(lines) && (strings.HasPrefix(lines[index], "  ") || lines[index] == "") {
				index++
			}
			continue
		}
		filtered = append(filtered, lines[index])
		index++
	}
	content = strings.Join(filtered, "\n")
	query := preloadQuery(config.ConnectionMode, config.Audio)
	if query == "" {
		return content
	}
	section := "preload:\n  " + yamlString(config.StreamID) + ": " + yamlString(query) + "\n"
	if marker := strings.Index(content, "homekit:\n"); marker >= 0 {
		return content[:marker] + section + content[marker:]
	}
	return strings.TrimRight(content, "\n") + "\n" + section
}

func ffmpegH264Template() string {
	return ffmpegH264TemplateFor(runtime.GOOS)
}

func ffmpegH264TemplateFor(goos string) string {
	if goos == "darwin" {
		// VideoToolbox can reject a compression session (-12908) even when its
		// encoder is advertised, which leaves HomeKit and MP4 consumers waiting
		// forever for an IDR. Prefer the deterministic software encoder for the
		// 720p camera fallback. Superfast + zerolatency, no B-frames,
		// scene-cut suppression and a one-second GOP keep startup bounded.
		// Do not clamp the shared stream to the 299 Kbps occasionally requested
		// by a single controller; that made snapshots and live video visibly
		// worse for every consumer. Repeating SPS/PPS on each IDR lets a newly
		// opened HomeKit session decode immediately.
		// Match source cadence (~20fps) so FFmpeg does not invent duplicated
		// frames while still emitting a 1s IDR for HomeKit mid-join.
		// `-tune zerolatency` enables sliced threading, which splits each frame
		// into ~10 slices at 720p. Apple Home's decoder cannot decode such
		// multi-slice frames and storms the accessory with FIR requests until it
		// tears the session down after ~30s, while the same encode at 360p (5
		// slices) plays fine. `-x264-params slices=1` alone is overridden by the
		// tune's sliced_threads, so pin threads=1 to force one slice per frame
		// while keeping zerolatency's no-frame-reordering semantics.
		return "-c:v libx264 -preset:v superfast -tune:v zerolatency -r:v 20 -g 20 -keyint_min 20 -sc_threshold 0 -bf 0 -profile:v main -level:v 4.0 -pix_fmt:v yuv420p -crf:v 23 -x264-params repeat-headers=1:threads=1 -flush_packets 1 -max_delay 0"
	}
	return ""
}

func (s XiaomiSource) URI() string {
	query := url.Values{"did": {s.DID}, "model": {s.Model}}
	if s.Subtype != "" {
		query.Set("subtype", s.Subtype)
	}
	// go2rtc treats any non-empty channel as the secondary lens and emits the
	// MISS videoquality2 command. HomeLoom uses channel 1 for the primary lens,
	// which therefore must be omitted from the upstream URI.
	if s.Channel > 1 {
		query.Set("channel", strconv.Itoa(s.Channel))
	}
	if s.ClientPublic != "" && s.ClientPrivate != "" && s.DevicePublic != "" && s.Sign != "" && s.Vendor != "" {
		query.Set("client_public", s.ClientPublic)
		query.Set("client_private", s.ClientPrivate)
		query.Set("device_public", s.DevicePublic)
		query.Set("sign", s.Sign)
		query.Set("vendor", s.Vendor)
		if s.UID != "" {
			query.Set("uid", s.UID)
		}
		return (&url.URL{Scheme: "xiaomi", Host: s.LocalIP, RawQuery: query.Encode()}).String()
	}
	return (&url.URL{Scheme: "xiaomi", User: url.UserPassword(s.UserID, s.Region), Host: s.LocalIP, RawQuery: query.Encode()}).String()
}

func publisherEnvironment(config PublisherConfig) []string {
	sourceURI := config.SourceURI
	if sourceURI == "" {
		sourceURI = config.Xiaomi.URI()
	}
	values := []string{
		sourceEnv(config) + "=" + sourceURI,
	}
	if config.PublishHomeKit {
		values = append(values, homeKitPINEnv(config)+"="+config.Secrets.HomeKitPIN)
	}
	if config.PublishHomeKit && config.Secrets.HomeKitDevicePrivate != "" {
		values = append(values, homeKitPrivateEnv(config)+"="+config.Secrets.HomeKitDevicePrivate)
	}
	return values
}

func sourceEnv(config PublisherConfig) string {
	return "HOMELOOM_CAMERA_SOURCE_" + envID(config.StreamID)
}
func homeKitPINEnv(config PublisherConfig) string {
	return "HOMELOOM_HAP_PIN_" + envID(config.StreamID)
}
func homeKitPrivateEnv(config PublisherConfig) string {
	return "HOMELOOM_HAP_PRIVATE_" + envID(config.StreamID)
}

func envID(id string) string {
	return strings.Map(func(r rune) rune {
		if r >= 'a' && r <= 'z' {
			return r - ('a' - 'A')
		}
		if (r >= 'A' && r <= 'Z') || (r >= '0' && r <= '9') {
			return r
		}
		return '_'
	}, id)
}
func validPublisherID(id string) bool {
	return id != "" && !strings.ContainsAny(id, "/\\\x00") && filepath.Base(id) == id
}
func allowedSourceScheme(scheme string) bool {
	return scheme == "rtsp" || scheme == "onvif" || scheme == "xiaomi"
}
func yamlString(value string) string { return strconv.Quote(value) }
