package tuya

import (
	"context"
	"crypto/rand"
	"encoding/hex"
	"errors"
	"net/http"
	"net/url"
	"strings"
	"sync"
	"time"

	tuyaapi "github.com/feranydev/homeloom/backend/internal/providers/tuya/api"
)

const (
	tuyaOAuthSessionTTL = 10 * time.Minute
)

// OAuthStartRequest contains the project credentials and the H5 authorization
// page configured in Tuya IoT Platform. Tuya does not expose a public
// consumer-App password/QR login API; the supported browser flow is OAuth 2.0
// authorization-code login, whose H5 URL is generated by the project.
type OAuthStartRequest struct {
	AccessID         string `json:"accessId"`
	AccessSecret     string `json:"accessSecret"`
	Region           string `json:"region,omitempty"`
	BaseURL          string `json:"baseUrl,omitempty"`
	AuthorizationURL string `json:"authorizationUrl"`
	RedirectURL      string `json:"redirectUrl"`
}

type OAuthStartResult struct {
	AuthorizationURL string    `json:"authorizationUrl"`
	State            string    `json:"state"`
	ExpiresAt        time.Time `json:"expiresAt"`
}

type OAuthCompleteRequest struct {
	State string `json:"state"`
	Code  string `json:"code"`
}

type OAuthCompleteResult struct {
	AccessToken  string    `json:"accessToken"`
	RefreshToken string    `json:"refreshToken"`
	UID          string    `json:"uid"`
	ExpiresAt    time.Time `json:"expiresAt"`
}

type oauthSession struct {
	accessID         string
	accessSecret     string
	baseURL          string
	authorizationURL string
	state            string
	expiresAt        time.Time
}

// OAuthService owns short-lived OAuth state and the project secret required
// to exchange a callback code. Sessions are memory-only and single-use; project
// credentials are never returned by Complete.
type OAuthService struct {
	mu         sync.Mutex
	sessions   map[string]oauthSession
	now        func() time.Time
	random     func([]byte) (int, error)
	httpClient func() *http.Client
}

func NewOAuthService() *OAuthService {
	return &OAuthService{sessions: make(map[string]oauthSession), now: time.Now, random: rand.Read}
}

func (s *OAuthService) Start(request OAuthStartRequest) (OAuthStartResult, error) {
	request.AccessID = strings.TrimSpace(request.AccessID)
	request.AccessSecret = strings.TrimSpace(request.AccessSecret)
	request.Region = strings.TrimSpace(request.Region)
	request.BaseURL = strings.TrimSpace(request.BaseURL)
	request.AuthorizationURL = strings.TrimSpace(request.AuthorizationURL)
	request.RedirectURL = strings.TrimSpace(request.RedirectURL)
	if request.AccessID == "" || request.AccessSecret == "" {
		return OAuthStartResult{}, errors.New("Tuya OAuth requires accessId and accessSecret")
	}
	if request.AuthorizationURL == "" {
		return OAuthStartResult{}, errors.New("Tuya OAuth authorizationUrl is required; configure the H5 authorization page in Tuya IoT Platform")
	}
	if err := absoluteHTTPURL(request.AuthorizationURL, "authorizationUrl"); err != nil {
		return OAuthStartResult{}, err
	}
	if err := absoluteHTTPURL(request.RedirectURL, "redirectUrl"); err != nil {
		return OAuthStartResult{}, err
	}
	if request.BaseURL == "" {
		request.BaseURL = regionBaseURL(request.Region)
	}
	if err := absoluteHTTPURL(request.BaseURL, "baseUrl"); err != nil {
		return OAuthStartResult{}, err
	}
	state, err := s.newState()
	if err != nil {
		return OAuthStartResult{}, err
	}
	now := s.currentTime()
	expiresAt := now.Add(tuyaOAuthSessionTTL)
	queryURL, err := url.Parse(request.AuthorizationURL)
	if err != nil {
		return OAuthStartResult{}, errors.New("Tuya OAuth authorizationUrl is invalid")
	}
	query := queryURL.Query()
	query.Set("client_id", request.AccessID)
	query.Set("redirect_uri", request.RedirectURL)
	query.Set("response_type", "code")
	query.Set("state", state)
	queryURL.RawQuery = query.Encode()

	s.mu.Lock()
	if s.sessions == nil {
		s.sessions = make(map[string]oauthSession)
	}
	s.cleanupLocked(now)
	s.sessions[state] = oauthSession{accessID: request.AccessID, accessSecret: request.AccessSecret, baseURL: request.BaseURL, authorizationURL: queryURL.String(), state: state, expiresAt: expiresAt}
	s.mu.Unlock()
	return OAuthStartResult{AuthorizationURL: queryURL.String(), State: state, ExpiresAt: expiresAt}, nil
}

func (s *OAuthService) Complete(ctx context.Context, request OAuthCompleteRequest) (OAuthCompleteResult, error) {
	state, code := strings.TrimSpace(request.State), strings.TrimSpace(request.Code)
	if state == "" || code == "" {
		return OAuthCompleteResult{}, errors.New("Tuya OAuth state and authorization code are required")
	}
	now := s.currentTime()
	s.mu.Lock()
	s.cleanupLocked(now)
	session, ok := s.sessions[state]
	if ok && session.state == state {
		// Consume the state before doing network I/O. OAuth callbacks can be
		// delivered more than once, and allowing two exchanges would permit a
		// concurrent replay of a one-time authorization code.
		delete(s.sessions, state)
	}
	s.mu.Unlock()
	if !ok || session.state != state {
		return OAuthCompleteResult{}, errors.New("Tuya OAuth state is missing or expired; start login again")
	}
	var httpClient *http.Client
	if s.httpClient != nil {
		httpClient = s.httpClient()
	}
	client, err := tuyaapi.NewClient(session.baseURL, session.accessID, session.accessSecret, httpClient)
	if err != nil {
		return OAuthCompleteResult{}, err
	}
	token, err := client.ExchangeAuthorizationCode(ctx, code)
	if err != nil {
		return OAuthCompleteResult{}, err
	}
	if strings.TrimSpace(token.UID) == "" {
		return OAuthCompleteResult{}, errors.New("Tuya OAuth token did not contain uid")
	}
	if strings.TrimSpace(token.RefreshToken) == "" {
		return OAuthCompleteResult{}, errors.New("Tuya OAuth token did not contain refresh_token")
	}
	if token.ExpiresIn <= 0 {
		return OAuthCompleteResult{}, errors.New("Tuya OAuth token did not contain a valid expiry")
	}
	expiresAt := s.currentTime().Add(time.Duration(token.ExpiresIn) * time.Second)
	return OAuthCompleteResult{AccessToken: token.AccessToken, RefreshToken: token.RefreshToken, UID: token.UID, ExpiresAt: expiresAt}, nil
}

func (s *OAuthService) AuthorizationURL(state string) (string, bool) {
	state = strings.TrimSpace(state)
	if state == "" {
		return "", false
	}
	now := s.currentTime()
	s.mu.Lock()
	defer s.mu.Unlock()
	s.cleanupLocked(now)
	session, ok := s.sessions[state]
	return session.authorizationURL, ok && session.state == state
}

func (s *OAuthService) newState() (string, error) {
	value := make([]byte, 24)
	random := s.random
	if random == nil {
		random = rand.Read
	}
	if _, err := random(value); err != nil {
		return "", errors.New("generate Tuya OAuth state failed")
	}
	return hex.EncodeToString(value), nil
}

func (s *OAuthService) currentTime() time.Time {
	if s.now != nil {
		return s.now()
	}
	return time.Now()
}

func (s *OAuthService) cleanupLocked(now time.Time) {
	for state, session := range s.sessions {
		if !now.Before(session.expiresAt) {
			delete(s.sessions, state)
		}
	}
}

func absoluteHTTPURL(value, field string) error {
	parsed, err := url.Parse(value)
	if err != nil || parsed.Host == "" || (parsed.Scheme != "http" && parsed.Scheme != "https") {
		return errors.New("Tuya OAuth " + field + " must be an absolute HTTP(S) URL")
	}
	return nil
}
